name: Update package version

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  update_version:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Check out the main branch
        run: git checkout main

      - name: Run _version.py
        run: python lair/_version.py

      - name: Commit changes
        run: |
          git config --local user.name "GitHub Actions"
          git config --local user.email "actions@github.com"
          git add lair/__init__.py
          git commit -m "auto-update package version"
          git push origin main
